name: Go CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # Verify dependencies
      - name: Install dependencies
        run: go mod tidy

      # Build app
      - name: Build
        run: go build -v ./...

      # Run tests
      - name: Test
        run: go test -v ./...
